version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME:-myuser} 
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:
