<<<<<<< HEAD
version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME:-myuser} 
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:

=======
services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    env_file:
      - clocked-in.env
    volumes:
      - clockedin_db_data:/var/lib/postgresql/data

volumes:
  clockedin_db_data:
>>>>>>> shift-service
